import { Table } from '@postcoil/ui';
import { Button } from 'antd';
import React from 'react';

import styles from './Fc002.module.scss';
import { TopBar } from './topBar/TopBar';

import CommonModal from '@/components/common/CommonModal';

// Table 임의 데이터
const columnsData = [
  {
    title: 'no',
    dataIndex: 'no',
    sorter: {
      compare: (a: any, b: any) => a.no - b.no,
      multiple: 3,
    },
  },
  {
    title: '코일 ID',
    dataIndex: 'id',
    sorter: {
      compare: (a: any, b: any) => a.id.localeCompare(b.id),
      multiple: 2,
    },
  },
  {
    title: '두께',
    dataIndex: 'length',
    sorter: {
      compare: (a: any, b: any) => a.length - b.length,
      multiple: 1,
    },
  },
  {
    title: '폭',
    dataIndex: 'width',
    sorter: {
      compare: (a: any, b: any) => a.width - b.width,
      multiple: 0,
    },
  },
];

const tableData = [
  {
    key: '1',
    no: '1',
    id: 'A001',
    length: 60,
    width: 70,
  },
  {
    key: '2',
    no: '2',
    id: 'A002',
    length: 66,
    width: 89,
  },
  {
    key: '3',
    no: '3',
    id: 'A003',
    length: 90,
    width: 70,
  },
];

// Table의 컬럼 정의
// const columnsData = [
//   {
//     title: 'No',
//     dataIndex: 'no',
//     key: 'no',
//     sorter: (a, b) => a.no.localeCompare(b.no),
//   },
//   {
//     title: '코일 ID',
//     dataIndex: 'id',
//     key: 'id',
//     sorter: (a, b) => a.id.localeCompare(b.id),
//   },
//   {
//     title: 'F 코드',
//     dataIndex: 'f_code',
//     key: 'f_code',
//     sorter: (a, b) => a.f_code.localeCompare(b.f_code),
//   },
//   {
//     title: '종류',
//     dataIndex: 'type',
//     key: 'type',
//     sorter: (a, b) => a.type.localeCompare(b.type),
//   },
//   {
//     title: '작업 코드',
//     dataIndex: 'op_code',
//     key: 'op_code',
//     sorter: (a, b) => a.op_code.localeCompare(b.op_code),
//   },
//   {
//     title: '상태',
//     dataIndex: 'status',
//     key: 'status',
//     sorter: (a, b) => a.status - b.status,
//   },
//   {
//     title: '현재 프로세스',
//     dataIndex: 'curr_proc',
//     key: 'curr_proc',
//     sorter: (a, b) => a.curr_proc.localeCompare(b.curr_proc),
//   },
//   {
//     title: '진행 상태',
//     dataIndex: 'progress',
//     key: 'progress',
//     sorter: (a, b) => a.progress.localeCompare(b.progress),
//   },
//   {
//     title: '두께',
//     dataIndex: 'thickness',
//     key: 'thickness',
//     sorter: (a, b) => a.thickness - b.thickness,
//   },
//   {
//     title: '폭',
//     dataIndex: 'width',
//     key: 'width',
//     sorter: (a, b) => a.width - b.width,
//   },
//   {
//     title: '외경',
//     dataIndex: 'outer',
//     key: 'outer',
//     sorter: (a, b) => a.outer - b.outer,
//   },
//   {
//     title: '내경',
//     dataIndex: 'inner',
//     key: 'inner',
//     sorter: (a, b) => a.inner - b.inner,
//   },
//   {
//     title: '중량',
//     dataIndex: 'weight',
//     key: 'weight',
//     sorter: (a, b) => a.weight - b.weight,
//   },
//   {
//     title: '총 중량',
//     dataIndex: 'total_weight',
//     key: 'total_weight',
//     sorter: (a, b) => a.total_weight - b.total_weight,
//   },
//   {
//     title: '길이',
//     dataIndex: 'length',
//     key: 'length',
//     sorter: (a, b) => a.length - b.length,
//   },
//   {
//     title: '통과 프로세스',
//     dataIndex: 'pass_proc',
//     key: 'pass_proc',
//     sorter: (a, b) => a.pass_proc.localeCompare(b.pass_proc),
//   },
//   {
//     title: '잔여 프로세스',
//     dataIndex: 'rem_proc',
//     key: 'rem_proc',
//     sorter: (a, b) => a.rem_proc.localeCompare(b.rem_proc),
//   },
//   {
//     title: '이전 프로세스',
//     dataIndex: 'pre_proc',
//     key: 'pre_proc',
//     sorter: (a, b) => a.pre_proc.localeCompare(b.pre_proc),
//   },
//   {
//     title: '다음 프로세스',
//     dataIndex: 'next_proc',
//     key: 'next_proc',
//     sorter: (a, b) => a.next_proc.localeCompare(b.next_proc),
//   },
//   {
//     title: '저장 위치',
//     dataIndex: 'storage_loc',
//     key: 'storage_loc',
//     sorter: (a, b) => a.storage_loc.localeCompare(b.storage_loc),
//   },
//   {
//     title: '야드',
//     dataIndex: 'yard',
//     key: 'yard',
//     sorter: (a, b) => a.yard.localeCompare(b.yard),
//   },
//   {
//     title: '코일 타입 코드',
//     dataIndex: 'coil_type_code',
//     key: 'coil_type_code',
//     sorter: (a, b) => a.coil_type_code.localeCompare(b.coil_type_code),
//   },
//   {
//     title: '주문 번호',
//     dataIndex: 'order_no',
//     key: 'order_no',
//     sorter: (a, b) => a.order_no.localeCompare(b.order_no),
//   },
// ];

// const tableData = [
//   {
//     key: '1',
//     id: '1',
//     no: 'HZ619410',
//     f_code: 'L',
//     type: 'H',
//     op_code: 'C',
//     status: 2,
//     curr_proc: '2PCM',
//     progress: 'H',
//     thickness: 3.74,
//     width: 685,
//     outer: 646,
//     inner: 20,
//     weight: 0.020111,
//     total_weight: 1760.75,
//     length: 87551.59,
//     pass_proc: 'None',
//     rem_proc: '2PCM1CAL1CGL201',
//     pre_proc: 'None',
//     next_proc: '1CAL',
//     storage_loc: '710511',
//     yard: '2PCMB',
//     coil_type_code: 'HTS400',
//     order_no: 'AD000',
//   },
//   {
//     key: '2',
//     id: '2',
//     no: 'HK616102',
//     f_code: 'L',
//     type: 'H',
//     op_code: 'C',
//     status: 2,
//     curr_proc: '2PCM',
//     progress: 'D',
//     thickness: 1.04,
//     width: 902,
//     outer: 448,
//     inner: 21,
//     weight: 0.007364,
//     total_weight: 1113.7,
//     length: 151235.74,
//     pass_proc: 'None',
//     rem_proc: '2PCM1CAL1CGL201',
//     pre_proc: 'None',
//     next_proc: '1CAL',
//     storage_loc: '410511',
//     yard: '2PCMA',
//     coil_type_code: 'HTS400',
//     order_no: 'CS014',
//   },
//   {
//     key: '3',
//     id: '3',
//     no: 'CI767589',
//     f_code: 'L',
//     type: 'C',
//     op_code: 'C',
//     status: 2,
//     curr_proc: '2EGL',
//     progress: 'D',
//     thickness: 1.42,
//     width: 1253,
//     outer: 359,
//     inner: 23,
//     weight: 0.013967,
//     total_weight: 991.55,
//     length: 70992.34,
//     pass_proc: '1PCM2CAL',
//     rem_proc: '2EGL201',
//     pre_proc: '2CAL',
//     next_proc: '201',
//     storage_loc: '911912',
//     yard: '2EGLA',
//     coil_type_code: 'HCKP',
//     order_no: 'EE028',
//   },
//   {
//     key: '4',
//     id: '4',
//     no: 'LX941827',
//     f_code: 'M',
//     type: 'D',
//     op_code: 'B',
//     status: 1,
//     curr_proc: '3CAL',
//     progress: 'A',
//     thickness: 2.1,
//     width: 580,
//     outer: 610,
//     inner: 18,
//     weight: 0.015843,
//     total_weight: 1345.2,
//     length: 82655.1,
//     pass_proc: '1EGL',
//     rem_proc: '3CAL201',
//     pre_proc: 'EGL',
//     next_proc: '201',
//     storage_loc: '812309',
//     yard: '3EGLA',
//     coil_type_code: 'HCT',
//     order_no: 'FF019',
//   },
//   {
//     key: '5',
//     id: '5',
//     no: 'MW104673',
//     f_code: 'L',
//     type: 'B',
//     op_code: 'A',
//     status: 3,
//     curr_proc: '2PCM',
//     progress: 'C',
//     thickness: 0.98,
//     width: 950,
//     outer: 400,
//     inner: 22,
//     weight: 0.009876,
//     total_weight: 885.45,
//     length: 64530.5,
//     pass_proc: '2PCM',
//     rem_proc: '3CAL',
//     pre_proc: 'PCM',
//     next_proc: 'CAL',
//     storage_loc: '903481',
//     yard: '2PCMA',
//     coil_type_code: 'HTC',
//     order_no: 'GG027',
//   },
//   {
//     key: '6',
//     id: '6',
//     no: 'NY738214',
//     f_code: 'H',
//     type: 'A',
//     op_code: 'B',
//     status: 1,
//     curr_proc: '1CAL',
//     progress: 'B',
//     thickness: 2.3,
//     width: 1020,
//     outer: 540,
//     inner: 24,
//     weight: 0.012456,
//     total_weight: 1120.8,
//     length: 74130.25,
//     pass_proc: 'CAL',
//     rem_proc: '2EGL',
//     pre_proc: 'CAL',
//     next_proc: 'EGL',
//     storage_loc: '554321',
//     yard: '2EGLA',
//     coil_type_code: 'HTS500',
//     order_no: 'HH023',
//   },
//   {
//     key: '7',
//     id: '7',
//     no: 'QZ875943',
//     f_code: 'N',
//     type: 'E',
//     op_code: 'D',
//     status: 3,
//     curr_proc: '3EGL',
//     progress: 'A',
//     thickness: 3.55,
//     width: 890,
//     outer: 560,
//     inner: 20,
//     weight: 0.025761,
//     total_weight: 1837.25,
//     length: 89243.5,
//     pass_proc: '1PCM',
//     rem_proc: '3EGL201',
//     pre_proc: 'PCM',
//     next_proc: 'EGL',
//     storage_loc: '633210',
//     yard: '3EGLB',
//     coil_type_code: 'HTS600',
//     order_no: 'II038',
//   },
//   {
//     key: '8',
//     id: '8',
//     no: 'RX946584',
//     f_code: 'K',
//     type: 'F',
//     op_code: 'C',
//     status: 2,
//     curr_proc: '2CAL',
//     progress: 'D',
//     thickness: 1.75,
//     width: 720,
//     outer: 490,
//     inner: 22,
//     weight: 0.014543,
//     total_weight: 1045.5,
//     length: 89052.9,
//     pass_proc: 'EGL',
//     rem_proc: '2CAL201',
//     pre_proc: 'EGL',
//     next_proc: 'CAL',
//     storage_loc: '932412',
//     yard: '2CALB',
//     coil_type_code: 'HTS700',
//     order_no: 'JJ014',
//   },
//   {
//     key: '9',
//     id: '9',
//     no: 'SY328496',
//     f_code: 'L',
//     type: 'D',
//     op_code: 'B',
//     status: 1,
//     curr_proc: '3PCM',
//     progress: 'A',
//     thickness: 1.2,
//     width: 810,
//     outer: 470,
//     inner: 19,
//     weight: 0.010321,
//     total_weight: 824.45,
//     length: 52985.6,
//     pass_proc: 'CAL',
//     rem_proc: '3PCM201',
//     pre_proc: 'PCM',
//     next_proc: 'EGL',
//     storage_loc: '783654',
//     yard: '3PCMA',
//     coil_type_code: 'HTS400',
//     order_no: 'KK020',
//   },
//   {
//     key: '10',
//     id: '10',
//     no: 'TZ453279',
//     f_code: 'M',
//     type: 'C',
//     op_code: 'D',
//     status: 3,
//     curr_proc: '1EGL',
//     progress: 'B',
//     thickness: 2.0,
//     width: 750,
//     outer: 530,
//     inner: 20,
//     weight: 0.017256,
//     total_weight: 1227.1,
//     length: 67840.2,
//     pass_proc: '3EGL',
//     rem_proc: '1EGL201',
//     pre_proc: 'EGL',
//     next_proc: 'PCM',
//     storage_loc: '665477',
//     yard: '1EGLB',
//     coil_type_code: 'HTS500',
//     order_no: 'LL027',
//   },
//   {
//     key: '11',
//     id: '11',
//     no: 'UZ974320',
//     f_code: 'N',
//     type: 'A',
//     op_code: 'A',
//     status: 2,
//     curr_proc: '2EGL',
//     progress: 'C',
//     thickness: 1.65,
//     width: 900,
//     outer: 485,
//     inner: 23,
//     weight: 0.013234,
//     total_weight: 982.45,
//     length: 69210.8,
//     pass_proc: '2EGL',
//     rem_proc: '2EGL201',
//     pre_proc: 'CAL',
//     next_proc: 'EGL',
//     storage_loc: '712965',
//     yard: '2EGLB',
//     coil_type_code: 'HTS600',
//     order_no: 'MM032',
//   },
//   {
//     key: '12',
//     id: '12',
//     no: 'VW592340',
//     f_code: 'L',
//     type: 'E',
//     op_code: 'C',
//     status: 1,
//     curr_proc: '3CAL',
//     progress: 'A',
//     thickness: 3.15,
//     width: 860,
//     outer: 500,
//     inner: 22,
//     weight: 0.022534,
//     total_weight: 1635.4,
//     length: 84295.6,
//     pass_proc: 'CAL',
//     rem_proc: '3CAL201',
//     pre_proc: 'CAL',
//     next_proc: 'EGL',
//     storage_loc: '844839',
//     yard: '3CALB',
//     coil_type_code: 'HTS700',
//     order_no: 'NN021',
//   },
//   {
//     key: '13',
//     id: '13',
//     no: 'WX239845',
//     f_code: 'K',
//     type: 'B',
//     op_code: 'D',
//     status: 2,
//     curr_proc: '2EGL',
//     progress: 'D',
//     thickness: 1.8,
//     width: 700,
//     outer: 510,
//     inner: 20,
//     weight: 0.016235,
//     total_weight: 1132.25,
//     length: 78365.7,
//     pass_proc: '1EGL',
//     rem_proc: '2EGL201',
//     pre_proc: 'EGL',
//     next_proc: 'CAL',
//     storage_loc: '934621',
//     yard: '2EGLA',
//     coil_type_code: 'HTS400',
//     order_no: 'OO039',
//   },
//   {
//     key: '14',
//     id: '14',
//     no: 'XY548970',
//     f_code: 'M',
//     type: 'D',
//     op_code: 'B',
//     status: 3,
//     curr_proc: '1PCM',
//     progress: 'C',
//     thickness: 2.25,
//     width: 980,
//     outer: 570,
//     inner: 24,
//     weight: 0.020123,
//     total_weight: 1578.65,
//     length: 81275.8,
//     pass_proc: '2PCM',
//     rem_proc: '1PCM201',
//     pre_proc: 'PCM',
//     next_proc: 'EGL',
//     storage_loc: '803219',
//     yard: '1PCMB',
//     coil_type_code: 'HTS500',
//     order_no: 'PP025',
//   },
//   {
//     key: '15',
//     id: '15',
//     no: 'YZ645321',
//     f_code: 'N',
//     type: 'C',
//     op_code: 'A',
//     status: 1,
//     curr_proc: '2CAL',
//     progress: 'B',
//     thickness: 1.9,
//     width: 870,
//     outer: 520,
//     inner: 21,
//     weight: 0.014877,
//     total_weight: 1290.75,
//     length: 75349.6,
//     pass_proc: 'EGL',
//     rem_proc: '2CAL201',
//     pre_proc: 'CAL',
//     next_proc: 'EGL',
//     storage_loc: '692745',
//     yard: '2CALB',
//     coil_type_code: 'HTS600',
//     order_no: 'QQ016',
//   },
//   {
//     key: '16',
//     id: '16',
//     no: 'ZA341678',
//     f_code: 'L',
//     type: 'E',
//     op_code: 'D',
//     status: 2,
//     curr_proc: '3EGL',
//     progress: 'D',
//     thickness: 1.55,
//     width: 910,
//     outer: 460,
//     inner: 22,
//     weight: 0.012678,
//     total_weight: 972.3,
//     length: 64487.2,
//     pass_proc: '2EGL',
//     rem_proc: '3EGL201',
//     pre_proc: 'EGL',
//     next_proc: 'CAL',
//     storage_loc: '804132',
//     yard: '3EGLA',
//     coil_type_code: 'HTS400',
//     order_no: 'RR029',
//   },
//   {
//     key: '17',
//     id: '17',
//     no: 'AB456789',
//     f_code: 'K',
//     type: 'F',
//     op_code: 'C',
//     status: 1,
//     curr_proc: '2EGL',
//     progress: 'A',
//     thickness: 2.45,
//     width: 930,
//     outer: 550,
//     inner: 23,
//     weight: 0.018756,
//     total_weight: 1390.9,
//     length: 81240.1,
//     pass_proc: 'EGL',
//     rem_proc: '2EGL201',
//     pre_proc: 'CAL',
//     next_proc: 'PCM',
//     storage_loc: '732100',
//     yard: '2EGLB',
//     coil_type_code: 'HTS700',
//     order_no: 'SS033',
//   },
//   {
//     key: '18',
//     id: '18',
//     no: 'BC567890',
//     f_code: 'L',
//     type: 'B',
//     op_code: 'D',
//     status: 2,
//     curr_proc: '1PCM',
//     progress: 'C',
//     thickness: 1.25,
//     width: 840,
//     outer: 480,
//     inner: 20,
//     weight: 0.011234,
//     total_weight: 945.6,
//     length: 69785.4,
//     pass_proc: 'PCM',
//     rem_proc: '1PCM201',
//     pre_proc: 'EGL',
//     next_proc: 'CAL',
//     storage_loc: '815420',
//     yard: '1PCM',
//     coil_type_code: 'HTS500',
//     order_no: 'TT022',
//   },
//   {
//     key: '19',
//     id: '19',
//     no: 'CD678901',
//     f_code: 'M',
//     type: 'D',
//     op_code: 'A',
//     status: 3,
//     curr_proc: '3EGL',
//     progress: 'B',
//     thickness: 2.7,
//     width: 1000,
//     outer: 600,
//     inner: 25,
//     weight: 0.023456,
//     total_weight: 1450.75,
//     length: 83217.9,
//     pass_proc: '2EGL',
//     rem_proc: '3EGL201',
//     pre_proc: 'CAL',
//     next_proc: 'EGL',
//     storage_loc: '804659',
//     yard: '3EGLB',
//     coil_type_code: 'HTS600',
//     order_no: 'UU031',
//   },
//   {
//     key: '20',
//     id: '20',
//     no: 'DE789012',
//     f_code: 'N',
//     type: 'A',
//     op_code: 'B',
//     status: 2,
//     curr_proc: '2CAL',
//     progress: 'A',
//     thickness: 1.85,
//     width: 870,
//     outer: 530,
//     inner: 22,
//     weight: 0.015678,
//     total_weight: 1325.4,
//     length: 76548.7,
//     pass_proc: 'CAL',
//     rem_proc: '2CAL201',
//     pre_proc: 'EGL',
//     next_proc: 'PCM',
//     storage_loc: '766543',
//     yard: '2CALB',
//     coil_type_code: 'HTS500',
//     order_no: 'VV026',
//   },
// ];

export const Fc002: React.FC = () => {
  const [isModalOpen, setIsModalOpen] = React.useState(false);
  const handleModalOpen = () => setIsModalOpen(true);
  const handleOk = () => {
    setIsModalOpen(false);
  };

  const handleCancel = () => {
    setIsModalOpen(false);
  };

  return (
    <div className={styles.boardContainer}>
      <h1>공정별 에러재 관리</h1>
      <TopBar />
      <div className={styles.result}>
        <div className={styles.table}>
          <Table
            useCheckBox={true}
            columns={columnsData}
            data={tableData}
            scroll={{ y: 450 }}
          />
        </div>
      </div>
      <Button type="primary" className={styles.btn} onClick={handleModalOpen}>
        에러패스
      </Button>
      <CommonModal
        title="에러패스 적용"
        isModalOpen={isModalOpen}
        onCancel={handleCancel}
        onApply={handleOk}>
        <p
          style={{
            fontSize: '1.5rem',
            textAlign: 'center',
            marginTop: '10px',
          }}>
          에러패스를 적용하시겠습니까?
        </p>
      </CommonModal>
    </div>
  );
};

export default Fc002;
