// Table Columns
export const columnsData = [
  {
    title: '번호',
    dataIndex: 'id',
    key: 'id',
  },
  {
    title: '코일 번호',
    dataIndex: 'no',
    key: 'no',
  },
  {
    title: '에러 코드',
    dataIndex: 'error_code',
    key: 'error_code',
  },
  {
    title: '에러 이유',
    dataIndex: 'error_reason',
    key: 'error_reason',
  },
  {
    title: '공장 코드',
    dataIndex: 'f_code',
    key: 'f_code',
  },
  {
    title: '재료 유형',
    dataIndex: 'type',
    key: 'type',
  },
  {
    title: '조업 코드',
    dataIndex: 'op_code',
    key: 'op_code',
  },
  {
    title: '상태',
    dataIndex: 'status',
    key: 'status',
  },
  {
    title: '진행 상황',
    dataIndex: 'progress',
    key: 'progress',
  },
  {
    title: '두께',
    dataIndex: 'thickness',
    key: 'thickness',
  },
  {
    title: '폭',
    dataIndex: 'width',
    key: 'width',
  },
  {
    title: '외경',
    dataIndex: 'outer',
    key: 'outer',
  },
  {
    title: '내경',
    dataIndex: 'inner',
    key: 'inner',
  },
  {
    title: '중량(kg/m)',
    dataIndex: 'weight',
    key: 'weight',
  },
  {
    title: '총 중량(kg)',
    dataIndex: 'total_weight',
    key: 'total_weight',
  },
  {
    title: '길이(mm)',
    dataIndex: 'length',
    key: 'length',
  },
  {
    title: '통과 공정',
    dataIndex: 'pass_proc',
    key: 'pass_proc',
  },
  {
    title: '잔여 공정',
    dataIndex: 'rem_proc',
    key: 'rem_proc',
  },
  {
    title: '이전 공정',
    dataIndex: 'pre_proc',
    key: 'pre_proc',
  },
  {
    title: '다음 공정',
    dataIndex: 'next_proc',
    key: 'next_proc',
  },
  {
    title: '보관 위치',
    dataIndex: 'storage_loc',
    key: 'storage_loc',
  },
  {
    title: '야적장',
    dataIndex: 'yard',
    key: 'yard',
  },
  {
    title: '코일 유형 코드',
    dataIndex: 'coil_type_code',
    key: 'coil_type_code',
  },
  {
    title: '주문 번호',
    dataIndex: 'order_no',
    key: 'order_no',
  },
];

// Table Date
export const tableData = [
  {
    key: '1',
    id: '1',
    no: 'HZ619410',
    f_code: 'L',
    type: 'H',
    op_code: 'C',
    status: '2',
    curr_proc: '2PCM',
    progress: 'H',
    thickness: 3.74,
    width: 685,
    outer: 646,
    inner: 20,
    weight: 0.020111,
    total_weight: 1760.75,
    length: 87551.59,
    pass_proc: 'None',
    rem_proc: '2PCM1CAL1CGL201',
    pre_proc: 'None',
    next_proc: '1CAL',
    storage_loc: '710511',
    yard: '2PCMB',
    coil_type_code: 'HTS400',
    order_no: 'AD000',
    error_code: 'E001',
    error_reason: '보류재',
  },
  {
    key: '2',
    id: '2',
    no: 'HK616102',
    f_code: 'L',
    type: 'H',
    op_code: 'C',
    status: '2',
    curr_proc: '2PCM',
    progress: 'D',
    thickness: 1.04,
    width: 902,
    outer: 448,
    inner: 21,
    weight: 0.007364,
    total_weight: 1113.7,
    length: 151235.74,
    pass_proc: 'None',
    rem_proc: '2PCM1CAL1CGL201',
    pre_proc: 'None',
    next_proc: '1CAL',
    storage_loc: '410511',
    yard: '2PCMA',
    coil_type_code: 'HTS400',
    order_no: 'AD001',
    error_code: 'E002',
    error_reason: '비축재',
  },
  {
    key: '3',
    id: '3',
    no: 'CI767589',
    f_code: 'L',
    type: 'C',
    op_code: 'C',
    status: '2',
    curr_proc: '2EGL',
    progress: 'D',
    thickness: 1.42,
    width: 1253,
    outer: 359,
    inner: 23,
    weight: 0.013967,
    total_weight: 991.55,
    length: 70992.34,
    pass_proc: '1PCM2CAL',
    rem_proc: '2EGL201',
    pre_proc: '2CAL',
    next_proc: '201',
    storage_loc: '911912',
    yard: '2EGLA',
    coil_type_code: 'HCKP',
    order_no: 'AA002',
    error_code: 'E003',
    error_reason: '설비사양 에러재- 폭',
  },
  {
    key: '4',
    id: '4',
    no: 'CG753141',
    f_code: 'L',
    type: 'C',
    op_code: 'C',
    status: '2',
    curr_proc: '2CAL',
    progress: 'D',
    thickness: 1.89,
    width: 880,
    outer: 584,
    inner: 20,
    weight: 0.013056,
    total_weight: 1848.24,
    length: 141562.5,
    pass_proc: '1PCM',
    rem_proc: '2CAL101',
    pre_proc: '1PCM',
    next_proc: '101',
    storage_loc: '531531',
    yard: '2CALA',
    coil_type_code: 'HTS800',
    order_no: 'AS003',
    error_code: 'E004',
    error_reason: '설비사양 에러재-두께',
  },
  {
    key: '5',
    id: '5',
    no: 'CI310730',
    f_code: 'L',
    type: 'C',
    op_code: 'C',
    status: '2',
    curr_proc: 'EGL',
    progress: 'D',
    thickness: 2.28,
    width: 1418,
    outer: 351,
    inner: 24,
    weight: 0.025379,
    total_weight: 1072.05,
    length: 42241.62,
    pass_proc: 'None',
    rem_proc: '2PCM1CAL1CGL201',
    pre_proc: 'None',
    next_proc: 'None',
    storage_loc: '330831',
    yard: 'EGLA',
    coil_type_code: 'HTS400',
    order_no: 'AC004',
    error_code: 'E005',
    error_reason: '관리재-자동차용도제약',
  },
  {
    key: '6',
    id: '6',
    no: 'CF859710',
    f_code: 'L',
    type: 'H',
    op_code: 'C',
    status: '2',
    curr_proc: '2PCM',
    progress: 'H',
    thickness: 2.84,
    width: 755,
    outer: 612,
    inner: 18,
    weight: 0.018652,
    total_weight: 1360.45,
    length: 92321.78,
    pass_proc: 'None',
    rem_proc: '2PCM1CAL1CGL101',
    pre_proc: 'None',
    next_proc: '1CAL',
    storage_loc: '710512',
    yard: '2PCMC',
    coil_type_code: 'HTS500',
    order_no: 'BS005',
    error_code: 'E006',
    error_reason: '관리재-표면엄격재',
  },
  {
    key: '7',
    id: '7',
    no: 'DA409812',
    f_code: 'L',
    type: 'C',
    op_code: 'C',
    status: '2',
    curr_proc: '2CAL',
    progress: 'D',
    thickness: 2.1,
    width: 765,
    outer: 500,
    inner: 22,
    weight: 0.017854,
    total_weight: 1500.23,
    length: 83901.87,
    pass_proc: '1PCM',
    rem_proc: '2CAL101',
    pre_proc: '1PCM',
    next_proc: '101',
    storage_loc: '631231',
    yard: '2CALB',
    coil_type_code: 'HTS700',
    order_no: 'AS006',
    error_code: 'E007',
    error_reason: '정보 이상재',
  },
  {
    key: '8',
    id: '8',
    no: 'HZ501021',
    f_code: 'L',
    type: 'H',
    op_code: 'C',
    status: '2',
    curr_proc: '2PCM',
    progress: 'H',
    thickness: 3.5,
    width: 680,
    outer: 600,
    inner: 19,
    weight: 0.01945,
    total_weight: 1700.4,
    length: 86510.23,
    pass_proc: 'None',
    rem_proc: '2PCM1CAL1CGL101',
    pre_proc: 'None',
    next_proc: '1CAL',
    storage_loc: '710513',
    yard: '2PCMC',
    coil_type_code: 'HTS500',
    order_no: 'BS007',
    error_code: 'E001',
    error_reason: '보류재',
  },
  {
    key: '9',
    id: '9',
    no: 'CI920837',
    f_code: 'L',
    type: 'C',
    op_code: 'C',
    status: '2',
    curr_proc: '2EGL',
    progress: 'D',
    thickness: 1.3,
    width: 1200,
    outer: 350,
    inner: 24,
    weight: 0.0149,
    total_weight: 980.0,
    length: 75000.0,
    pass_proc: '1PCM2CAL',
    rem_proc: '2EGL201',
    pre_proc: '2CAL',
    next_proc: '201',
    storage_loc: '911913',
    yard: '2EGLA',
    coil_type_code: 'HCKP',
    order_no: 'AA008',
    error_code: 'E003',
    error_reason: '설비사양 에러재- 폭',
  },
  {
    key: '10',
    id: '10',
    no: 'HK305148',
    f_code: 'L',
    type: 'H',
    op_code: 'C',
    status: '2',
    curr_proc: '2PCM',
    progress: 'D',
    thickness: 1.2,
    width: 900,
    outer: 450,
    inner: 22,
    weight: 0.008,
    total_weight: 1120.0,
    length: 140000.0,
    pass_proc: 'None',
    rem_proc: '2PCM1CAL1CGL201',
    pre_proc: 'None',
    next_proc: '1CAL',
    storage_loc: '420512',
    yard: '2PCMA',
    coil_type_code: 'HTS400',
    order_no: 'AD009',
    error_code: 'E002',
    error_reason: '비축재',
  },
  {
    key: '11',
    id: '11',
    no: 'CF859711',
    f_code: 'L',
    type: 'H',
    op_code: 'C',
    status: '2',
    curr_proc: '2PCM',
    progress: 'H',
    thickness: 2.84,
    width: 755,
    outer: 612,
    inner: 18,
    weight: 0.018652,
    total_weight: 1360.45,
    length: 92321.78,
    pass_proc: 'None',
    rem_proc: '2PCM1CAL1CGL101',
    pre_proc: 'None',
    next_proc: '1CAL',
    storage_loc: '710512',
    yard: '2PCMC',
    coil_type_code: 'HTS500',
    order_no: 'BS005',
    error_code: 'E006',
    error_reason: '관리재-표면엄격재',
  },
  {
    key: '12',
    id: '12',
    no: 'CG861492',
    f_code: 'L',
    type: 'C',
    op_code: 'C',
    status: '2',
    curr_proc: '2CAL',
    progress: 'D',
    thickness: 2.0,
    width: 880,
    outer: 500,
    inner: 20,
    weight: 0.013056,
    total_weight: 1500.0,
    length: 140000.0,
    pass_proc: '1PCM',
    rem_proc: '2CAL101',
    pre_proc: '1PCM',
    next_proc: '101',
    storage_loc: '531531',
    yard: '2CALA',
    coil_type_code: 'HTS800',
    order_no: 'AS010',
    error_code: 'E004',
    error_reason: '설비사양 에러재-두께',
  },
  {
    key: '13',
    id: '13',
    no: 'CI310731',
    f_code: 'L',
    type: 'C',
    op_code: 'C',
    status: '2',
    curr_proc: 'EGL',
    progress: 'D',
    thickness: 2.28,
    width: 1418,
    outer: 351,
    inner: 24,
    weight: 0.025379,
    total_weight: 1072.05,
    length: 42241.62,
    pass_proc: 'None',
    rem_proc: '2PCM1CAL1CGL201',
    pre_proc: 'None',
    next_proc: 'None',
    storage_loc: '330832',
    yard: 'EGLA',
    coil_type_code: 'HTS400',
    order_no: 'AC011',
    error_code: 'E005',
    error_reason: '관리재-자동차용도제약',
  },
  {
    key: '14',
    id: '14',
    no: 'DA409813',
    f_code: 'L',
    type: 'C',
    op_code: 'C',
    status: '2',
    curr_proc: '2CAL',
    progress: 'D',
    thickness: 2.1,
    width: 765,
    outer: 500,
    inner: 22,
    weight: 0.017854,
    total_weight: 1500.23,
    length: 83901.87,
    pass_proc: '1PCM',
    rem_proc: '2CAL101',
    pre_proc: '1PCM',
    next_proc: '101',
    storage_loc: '631232',
    yard: '2CALB',
    coil_type_code: 'HTS700',
    order_no: 'AS012',
    error_code: 'E007',
    error_reason: '정보 이상재',
  },
  {
    key: '15',
    id: '15',
    no: 'HZ501022',
    f_code: 'L',
    type: 'H',
    op_code: 'C',
    status: '2',
    curr_proc: '2PCM',
    progress: 'H',
    thickness: 3.5,
    width: 680,
    outer: 600,
    inner: 19,
    weight: 0.01945,
    total_weight: 1700.4,
    length: 86510.23,
    pass_proc: 'None',
    rem_proc: '2PCM1CAL1CGL101',
    pre_proc: 'None',
    next_proc: '1CAL',
    storage_loc: '710514',
    yard: '2PCMC',
    coil_type_code: 'HTS500',
    order_no: 'BS013',
    error_code: 'E001',
    error_reason: '보류재',
  },
];
